server:
  # 我这里指定 6000 会发现起来之后不能访问到
  port: 8080
logging:
  level:
    root: info
    # 可以打印 sql
    com.liukai.eshop.inventory: info
    com.baomidou.mybatisplus: debug
# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(aLfHJooH7jVYnA3iqtdMt4tvkn1eYdUbnqyhLS+5h/pK5lHqkBP/KfcxxlPUI2Q5Fb2jphQsuXP/PewuacfZIPbaohy6iMx7puiX99+TtKHdZDv6gHHYaPA0+fogMrmC5hTObpm1ve5GD18/IEhkyy1XDo92XPjeeM7SxT6RCd2tfFP7QO30W9pZmjQkO2y79K+IjZzVUSNVO+OLaNexFtMXHYe5bL9QRkumyZcFxMgByMMN8qEbnGFR4BGInp/Y)
    username: ENC(kZ3hpwvQ3769+6JoU+f4BuN8ycfaYEiLQ1Zq7vDJQVOLIVI4ohN3gU5PLYDhE6GJ)
    password: ENC(rEGN76ySzkPj8rzkAULdp91KpXBy2u42KTyb+jhbuQFd18m+wJ2ioxnKeA5rzDvP)

  # redis 配置
  redis:
    #    cluster:
    #      nodes:
    #        - XX:XX
    #
    #      max-redirects: 3  # 获取失败 最大重定向次数
    timeout: 6000 # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    host: ENC(RBZTXY1qT1QNPZEShS2+uADER6CG3vXnX7s+ZdyurCZVf5rw0ClBoqJMrTfbC57k)
    port: ENC(NRbbtdxTdn0ThS/z2EFDg/ZAxEh6LhlQU4IIfk0SNBzaLXTwgfwVFcS7hYNnVYUF)
    password: ENC(15pHOBVxjG2BBPYib/rNlfnl4VdnX21VAsdNq3VcFs18o3cjdPSFyrJ5aBsSL+ua)
#  mapper-locations: classpath*:mapper/*.xml

# 数据库配置信息加密
#jasypt:
#  encryptor:
#        password: 1
